[tox]
envlist =
    lint
    py3{10,11,12,13,14}
    combine-test-reports
isolated_build = True


[testenv]
description = Run unit tests.
package = wheel
setenv =
    PY_IGNORE_IMPORTMISMATCH=1 # https://github.com/pytest-dev/pytest/issues/2042
    COVERAGE_FILE = reports{/}.coverage.{envname}
    COVERAGE_PROCESS_START = {toxinidir}/pyproject.toml
    SETUPTOOLS_SHIM = 1
commands =
    # Run tests from .py files
    pytest --junitxml=reports/pytest.xml.{envname} {posargs}

[testenv:py310]
basepython = python3.10
deps =
    -r requirements-310.txt

[testenv:py311]
basepython = python3.11
deps =
    -r requirements-311.txt

[testenv:py312]
basepython = python3.12
deps =
    -r requirements-312.txt

[testenv:py313]
basepython = python3.13
deps =
    -r requirements-313.txt

[testenv:py314]
basepython = python3.14
deps =
    -r requirements-314.txt

[testenv:lint]
description = Run static checkers.
basepython = python3.10
deps =
    -r requirements-lint.txt
commands =
    ruff format . --check
    ruff check .
    mypy .


[testenv:combine-test-reports]
description = Combine test and coverage data from multiple test runs.
skip_install = true
setenv =
    COVERAGE_FILE = reports/.coverage
depends = py3
deps =
    junitparser
    coverage[toml]
commands =
    junitparser merge --glob reports/pytest.xml.* reports/pytest.xml
    coverage combine --keep
    coverage html
